"use client";

import "./global.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material";
import { appTheme } from "@/utils";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <ThemeProvider theme={appTheme}>
          <body>{children}</body>
        </ThemeProvider>
      </QueryClientProvider>
    </html>
  );
}
