import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material";
import { appTheme } from "@/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={appTheme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
